blank_issues_enabled: false
contact_links:
  - name: General questions
    url: https://github.com/uct-eresearch/eresearch-documentation
    about: Use discussions or contact support for general queries